import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ContratarTeamProvider } from './team/contratar'
import { ContratarContactProvider } from "./contact/contratar";

export const metadata: Metadata = {
  title: "DashStack",
  description: "Generated by create next app",
  icons: {
    icon: "/Logo.svg"
  }
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <ContratarTeamProvider>
          <ContratarContactProvider>
            {children}

            <Toaster toastOptions={{
              style: {
                userSelect: "none"
              }
            }}/>
          </ContratarContactProvider>
        </ContratarTeamProvider>
      </body>
    </html>
  );
}
